export const GET_SEARCH_USERS = "GET_SEARCH_USERS";
export const ADD_FRIEND = "ADD_FRIEND";
export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const UPDATE_CHATS = "UPDATE_CHATS"
export const DELETE_MESSAGES_CHAT="DELETE_MESSAGES_CHAT"
export const SET_SHOW_SETTINGS_GROUP = "SET_SHOW_SETTINGS_GROUP";
export const SET_SHOW_ADD_GROUP = "SET_SHOW_ADD_GROUP";
export const UPDATE_MEMBERS_GROUP = "UPDATE_MEMBERS_GROUP";